use_frameworks!

platform :ios, '9.0'

target 'Extension_Example' do
  pod 'Extension', :path => '../'

  target 'Extension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
